"""Add RecommendationLog table

Revision ID: 16668ae4a277
Revises: 2ce0504710f4
Create Date: 2025-05-03 17:26:22.124780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16668ae4a277'
down_revision: Union[str, None] = '2ce0504710f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('current_t_set', sa.Integer(), nullable=True),
    sa.Column('current_power', sa.Float(), nullable=True),
    sa.Column('optimal_t_set', sa.Integer(), nullable=True),
    sa.Column('predicted_power', sa.Float(), nullable=True),
    sa.Column('estimated_saving', sa.Float(), nullable=True),
    sa.Column('recommendation_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_log_id'), 'recommendation_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_log_id'), table_name='recommendation_log')
    op.drop_table('recommendation_log')
    # ### end Alembic commands ###
