"""Add PMV log table

Revision ID: 28d29239bb9c
Revises: 84979420af7d
Create Date: 2025-05-04 10:25:47.331165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d29239bb9c'
down_revision: Union[str, None] = '84979420af7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pmv_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pmv', sa.Float(), nullable=True),
    sa.Column('ppd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pmv_log_id'), 'pmv_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pmv_log_id'), table_name='pmv_log')
    op.drop_table('pmv_log')
    # ### end Alembic commands ###
