"""Add t_indoor and h_indoor to pmv_log

Revision ID: 5bd3d6703520
Revises: 28d29239bb9c
Create Date: 2025-05-04 11:10:13.249516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd3d6703520'
down_revision: Union[str, None] = '28d29239bb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pmv_log', sa.Column('t_indoor', sa.Float(), nullable=True))
    op.add_column('pmv_log', sa.Column('h_indoor', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pmv_log', 'h_indoor')
    op.drop_column('pmv_log', 't_indoor')
    # ### end Alembic commands ###
