"""Add EmissionLog table

Revision ID: 84979420af7d
Revises: 16668ae4a277
Create Date: 2025-05-03 18:48:27.626308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84979420af7d'
down_revision: Union[str, None] = '16668ae4a277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('emission', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_log_id'), 'emission_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emission_log_id'), table_name='emission_log')
    op.drop_table('emission_log')
    # ### end Alembic commands ###
